### PR TITLE
Improve Documentation Accessibility

### PR DESCRIPTION
**Pull request by cryptosvinarnik**
In this PR, I've made some updates to the documentation to improve its accessibility. 

In this PR, I've updated the `send.mdx` documentation. I've added a quick access link to the `IMailbox` interface source code, improving the reading experience. I've also corrected the `onlyMailbox` modifier example. These changes enhance clarity and accessibility.

### CODE REVIEW

**Comment by cryptosvinarnik** [comment]
@avious00

**Comment by avious00** [comment]
hey @cryptosvinarnik thanks for your contribution! I'll have an engineer review it

**Comment by aroralanuk** [comment]
I would put the "check IMailbox" reference inside the collapsible section, but otherwise LGTM.

**Comment by cryptosvinarnik** [comment]
@aroralanuk

**Comment by cryptosvinarnik** [comment]
@aroralanuk

**Comment by cryptosvinarnik** [comment]
@avious00

**Comment by edakturk14** [comment]
hey @cryptosvinarnik - this is great! thank you for the suggestion. we've updated the docs to have the mailbox interface and the related send/receive func references. Please let us know if you have any other suggestions!

**Pull request closed without merging**
